name: Push to main
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Trestle
      run: bash scripts/automation/install_trestle.sh
    - name: Release
      run: source scripts/automation/release.sh
    - name: Push the changes
      run: bash scripts/automation/push.sh
  downstream-repo-update:
    name: Update downstream repositories
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Clone branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main
        token: ${{ secrets.GIT_TOKEN }}
    - name: Determine initialization status
      id: determine_initialization_status
      run: |
        set +e
        bash scripts/automation/check_profile.sh
        exitcode="$?"
        echo "exitcode: $exitcode"
        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
    - name: Clone downstream repo
      if: steps.determine_initialization_status.outputs.exitcode == '1'
      uses: actions/checkout@v2
      with:
        repository: my-repo-base/my-component-definition
        path: './my-component-definition'
        token: ${{ secrets.GIT_TOKEN }}
        fetch-depth: 0
    - name: Update downstream
      if: steps.determine_initialization_status.outputs.exitcode == '1'
      run: bash scripts/automation/update_downstream.sh
      env:
        GH_TOKEN: ${{ secrets.GIT_TOKEN }}
  merge-main-to-develop:
    name: Merge main to develop
    runs-on: ubuntu-latest
    needs: release
    concurrency: 
      group: ${{ github.ref }}-${{ github.workflow }}-${{ github.job }}-main
      cancel-in-progress: true
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        source-branch: main
        target-branch: develop
        commit-message: "chore: Merge back version tags and changelog into develop."
